version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2-apache
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
